services:
  web:
    image: docker.io/wger/server:latest
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/static:/home/wger/static
      - ${DATA_PATH}/media:/home/wger/media
    expose:
      - 8000
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 5
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  powersync:
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy

  nginx:
    image: docker.io/nginx:stable
    container_name: wger
    depends_on:
      - web
      - powersync
    volumes:
      - ${CONFIG_PATH}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${DATA_PATH}/static:/wger/static:ro
      - ${DATA_PATH}/media:/wger/media:ro
    ports:
      - "${EXT_PORT}:80"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default
      - homepage-network

  db:
    image: docker.io/postgres:15-alpine
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - POSTGRES_DB=${DJANGO_DB_DATABASE}
      - TZ
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 5
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wger" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cache:
    image: docker.io/redis
    expose:
      - 6379
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 5
    volumes:
      - ${CONFIG_PATH}/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    mem_limit: 4gb

  celery_worker:
    image: docker.io/wger/server:latest
    command: /start-worker
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/media:/home/wger/media
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 5
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "wger", "inspect", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_beat:
    image: docker.io/wger/server:latest
    command: /start-beat
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 5
    volumes:
      - celery-beat:/home/wger/beat/
    env_file:
      - .env
    depends_on:
      celery_worker:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data:
  celery-beat:
  redis-data:

  # Heads up, if you remove these volumes and use folders directly you need to chown them
  # to the UID and GID 1000 even if it doesn't exist on your system. Also, they should
  # be readable by everyone.
  #
  # https://wger.readthedocs.io/en/latest/production/docker.html#missing-static-files
  # media:
  # static:

networks:
  default:
    name: wger_network
  homepage-network:
    external: true

include:
  - path: ${DATA_PATH}/services/postgres.yaml
  - path: ${DATA_PATH}/services/powersync.yaml
  - path: ${DATA_PATH}/services/redis.yaml
