services:
  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ${FRESHRSS_PATH}/data:/var/www/FreshRSS/data
      - ${FRESHRSS_PATH}/extensions:/var/www/FreshRSS/extensions
    ports:
      - "${PUBLISHED_PORT}:80"
    environment:
      TZ: ${TZ}
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      TRUSTED_PROXY: 172.16.0.1/12 
      OIDC_ENABLED: 0
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3
    networks:
      - default
      - homepage-network

networks:
  homepage-network:
    external: true
