services:
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    ports:
      - ${EXT_PORT}:80
    networks:
      - homepage-network
    restart: unless-stopped

networks:
  homepage-network:
    external: true

